apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoapp.fullname" . }}-config
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
data:
  PYTHONUNBUFFERED: {{ .Values.env.PYTHONUNBUFFERED | quote }}
