{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.fullname" . }}-mysql
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
