{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todoapp.fullname" . }}-data
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ include "todoapp.fullname" . }}-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "todoapp.fullname" . }}-data
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.persistence.size }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end }}
